### ISSUE TITLE
Implement quasar-calendar

### ISSUE THREAD

**Issue by tommycox** [Decentralize-Colorado/Decentralize-Colorado#2]
Usage and Examples: https://vuejsexamples.com/a-vue-js-calendar-using-the-quasar-framework-that-implements-monthly-and-agenda-views/

Demo: https://stormseed.github.io/quasar-calendar-demo/

Github: https://github.com/stormseed/quasar-calendar

**Comment by NukeManDan** [comment]
7b7777c closes #2
